# Generated by Django 4.1.6 on 2023-02-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=8)),
                ('date', models.DateField()),
            ],
        ),
    ]
